import {
  LayoutDashboard,
  Monitor,
  ShieldAlert,
  AlertTriangle,
  Bug,
  FileText,
  BarChart2,
  FileSearch,
  Bell,
  BookOpen,
  Users,
  CheckSquare,
  Scan,
  Target,
  Wrench,
  Lock,
  Star,
  ClipboardList,
  Server,
  Layers,
  Zap,
  Network,
  BarChart,
} from 'lucide-react'
import {
  CrowdStrikeLogo,
  WazuhLogo,
  Outpost24Logo,
  KeeperLogo,
  ZabbixLogo,
} from '@/icons'
import type { PlatformConfig, PlatformId } from '@/types'

export const PLATFORM_REGISTRY: Record<PlatformId, PlatformConfig> = {
  crowdstrike: {
    id: 'crowdstrike',
    name: 'CrowdStrike',
    category: 'Endpoint Detection & Response',
    Logo: CrowdStrikeLogo,
    colors: {
      primary: '#1D6AE5',
      secondary: '#2A7FFF',
      glow: 'rgba(29, 106, 229, 0.25)',
      gradient: 'linear-gradient(135deg, #1D6AE5 0%, #0F3F8C 100%)',
    },
    defaultRoute: '/crowdstrike/dashboard',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/crowdstrike/dashboard', badge: { text: 'Live', variant: 'green' } },
      { id: 'endpoints', label: 'Endpoints', icon: Monitor, path: '/crowdstrike/endpoints' },
      { id: 'detections', label: 'Detections', icon: ShieldAlert, path: '/crowdstrike/detections' },
      { id: 'incidents', label: 'Incidents', icon: AlertTriangle, path: '/crowdstrike/incidents' },
      { id: 'vulnerabilities', label: 'Vulnerabilities', icon: Bug, path: '/crowdstrike/vulnerabilities' },
      { id: 'policies', label: 'Policies', icon: FileText, path: '/crowdstrike/policies' },
      { id: 'reports', label: 'Reports', icon: BarChart2, path: '/crowdstrike/reports' },
    ],
  },

  wazuh: {
    id: 'wazuh',
    name: 'SIEM',
    category: 'Security Information & Event Management',
    Logo: WazuhLogo,
    colors: {
      primary: '#7C3AED',
      secondary: '#9D5CFF',
      glow: 'rgba(124, 58, 237, 0.25)',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)',
    },
    defaultRoute: '/wazuh/dashboard',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/wazuh/dashboard', badge: { text: 'Live', variant: 'green' } },
      { id: 'log-analysis', label: 'Log Analysis', icon: FileSearch, path: '/wazuh/log-analysis' },
      { id: 'alerts', label: 'Alerts', icon: Bell, path: '/wazuh/alerts', badge: { text: '12', variant: 'orange' } },
      { id: 'rule-monitoring', label: 'Rule Monitoring', icon: BookOpen, path: '/wazuh/rule-monitoring' },
      { id: 'agents', label: 'Agents', icon: Users, path: '/wazuh/agents' },
      { id: 'compliance', label: 'Compliance', icon: CheckSquare, path: '/wazuh/compliance' },
      { id: 'reports', label: 'Reports', icon: BarChart2, path: '/wazuh/reports' },
    ],
  },

  outpost24: {
    id: 'outpost24',
    name: 'Outpost24',
    category: 'Vulnerability Management',
    Logo: Outpost24Logo,
    colors: {
      primary: '#EA580C',
      secondary: '#F97316',
      glow: 'rgba(234, 88, 12, 0.25)',
      gradient: 'linear-gradient(135deg, #EA580C 0%, #7C2D12 100%)',
    },
    defaultRoute: '/outpost24/dashboard',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/outpost24/dashboard', badge: { text: 'Live', variant: 'green' } },
      { id: 'scan-results', label: 'Scan Results', icon: Scan, path: '/outpost24/scan-results' },
      { id: 'cve-analysis', label: 'CVE Analysis', icon: Bug, path: '/outpost24/cve-analysis', badge: { text: 'New', variant: 'blue' } },
      { id: 'risk-scoring', label: 'Risk Scoring', icon: Target, path: '/outpost24/risk-scoring' },
      { id: 'remediation', label: 'Remediation', icon: Wrench, path: '/outpost24/remediation', badge: { text: '4', variant: 'orange' } },
      { id: 'reports', label: 'Reports', icon: BarChart2, path: '/outpost24/reports' },
    ],
  },

  keeper: {
    id: 'keeper',
    name: 'Keeper',
    category: 'Password Security',
    Logo: KeeperLogo,
    colors: {
      primary: '#16A34A',
      secondary: '#22C55E',
      glow: 'rgba(22, 163, 74, 0.25)',
      gradient: 'linear-gradient(135deg, #16A34A 0%, #14532D 100%)',
    },
    defaultRoute: '/keeper/dashboard',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/keeper/dashboard', badge: { text: 'Live', variant: 'green' } },
      { id: 'weak-passwords', label: 'Weak Passwords', icon: Lock, path: '/keeper/weak-passwords', badge: { text: '20', variant: 'red' } },
      { id: 'security-score', label: 'Security Score', icon: Star, path: '/keeper/security-score' },
      { id: 'user-audit', label: 'User Audit', icon: Users, path: '/keeper/user-audit' },
      { id: 'policy-compliance', label: 'Policy Compliance', icon: ClipboardList, path: '/keeper/policy-compliance' },
      { id: 'reports', label: 'Reports', icon: BarChart2, path: '/keeper/reports' },
    ],
  },

  zabbix: {
    id: 'zabbix',
    name: 'Zabbix',
    category: 'Infrastructure Monitoring',
    Logo: ZabbixLogo,
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      glow: 'rgba(220, 38, 38, 0.25)',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #7F1D1D 100%)',
    },
    defaultRoute: '/zabbix/dashboard',
    nav: [
      { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/zabbix/dashboard', badge: { text: 'Live', variant: 'green' } },
      { id: 'host-availability', label: 'Host Availability', icon: Server, path: '/zabbix/host-availability' },
      { id: 'host-groups', label: 'Host Groups', icon: Layers, path: '/zabbix/host-groups' },
      { id: 'triggers', label: 'Triggers', icon: Zap, path: '/zabbix/triggers', badge: { text: '5', variant: 'red' } },
      { id: 'network-monitoring', label: 'Network Monitoring', icon: Network, path: '/zabbix/network-monitoring' },
      { id: 'sla-reports', label: 'SLA Reports', icon: BarChart, path: '/zabbix/sla-reports' },
      { id: 'reports', label: 'Reports', icon: BarChart2, path: '/zabbix/reports' },
    ],
  },
}

export const PLATFORM_LIST = Object.values(PLATFORM_REGISTRY)
